# Generated by Django 3.1.3 on 2020-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_sheet',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.AddField(
            model_name='answer_sheet',
            name='right',
            field=models.BooleanField(default=True),
        ),
    ]
