# Generated by Django 3.1.3 on 2020-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201212_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='i',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
