# Generated by Django 3.1.3 on 2020-12-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='autor',
            new_name='author',
        ),
    ]
