# Generated by Django 3.1.3 on 2020-12-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
