# Generated by Django 3.1.3 on 2020-12-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201223_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_sheet',
            name='Result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.result'),
        ),
        migrations.AlterField(
            model_name='answer_sheet',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
